#! /bin/sh

# ] ---- AUTOSTART ---- [

sxhkd &
feh --bg-fill ~/Imágenes/Wall.png &
flameshot &
picom -b &
nm-applet &
sh ~/.config/polybar/launch.sh

# ] ---- WORKSPACES ---- [ 

bspc monitor -d "~" 1 2 3 4 5

# ] ---- WINDOW CONFIG ---- [

bspc config border_width         2
bspc config window_gap         	13

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr

bspc rule -a qutebrowser desktop=^6 follow=on
bspc rule -a emacs desktop=^3 follow=on
bspc rule -a spotify desktop=^2 follow=on
