#! /bin/sh

# ] ---- AUTOSTART ---- [

setxkbmap -option keypad:pointerkeys &
xset r rate 200 25 &
sxhkd &
wmname LG3D &
feh --bg-fill ~/Imágenes/Wall3.png &
flameshot &
picom -b &
nm-applet &
dunst &
unclutter -idle 3 &
sh ~/.config/polybar/launch.sh &
xdo raise -N Polybar

# ] ---- WORKSPACES ---- [ 

bspc monitor -d "~" 1 2 3 4 5

# ] ---- WINDOW CONFIG ---- [

bspc config border_width         3
bspc config window_gap         	13

bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#6272a4"

bspc config border_radius        15
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr
